### PR TITLE
fix: removed the useless use of the spritesheetloader

### PR DESCRIPTION
**Pull request by NaejDoree**

### CODE REVIEW

**Comment by Tzupy** [comment]
@NaejDoree If you removed the sprite sheet loaders how are assets loaded anymore? They still work with your change 🤔

**Comment by CGjupoulton** [comment]
@Tzupy The SpriteSheetLoader was loading them, but they were never used. The spritesheets that **were** being used were defined by the json files placed in the assets folder.

Spritesheets can be splitted into individual images either thanks to an accompanying json (PIXI does this by itself), or the GraphicEntityModule will do it if you use a SpriteSheetLoader. Really, it should be called SpriteSheetSplitter...

**Comment by Tzupy** [comment]
@CGjupoulton Yeah, splitter would make more sense.

So the engine (GraphicEntityModule) just looks for json files and does the loading itself?

**Comment by CGjupoulton** [comment]
@Tzupy no, the GraphicEntityModule doesn't load anything. It merely uses things that are preloaded by PIXI.js (the rendering engine) from the assets folder.

**Comment by CGjupoulton** [comment]
@Tzupy the only times it does any loading is at runtime with the spritesheetloader

**Comment by Tzupy** [comment]
@CGjupoulton Ok, got it now. Thanks for the explanation!

**Pull request merged**
